### ISSUE TITLE
Plan to take over development and maintenance of the stylelint-a11y package

### ISSUE THREAD

**Issue by schalkneethling** [mechanical-ink/stylelint-a11y#1]
Please have a look at the following links for more details. 

- https://github.com/YozhikM/stylelint-a11y/issues/69
- https://github.com/stylelint/stylelint/issues/6212#issuecomment-1705744761

If you are interested in being part of the work going forward, please either add a 👍 or leave a comment explaining how you would like to participate. I look forward to getting this going and getting it released as soon as we can.

**Comment by ronilaukkarinen** [comment]
I'm open for this and could be a co-maintainer. We use [my fork](https://github.com/ronilaukkarinen/stylelint-a11y/) in [our company](https://github.com/digitoimistodude) and I've been trying to keep my fork as up to date as I can. It's currently in stylelint 15 and [the migration work for 16](https://stylelint.io/migration-guide/to-16/) is scheduled for Jan-Feb.

**Comment by schalkneethling** [comment]
> I'm open for this and could be a co-maintainer. We use [my fork](https://github.com/ronilaukkarinen/stylelint-a11y/) in [our company](https://github.com/digitoimistodude) and I've been trying to keep my fork as up to date as I can. It's currently in stylelint 15 and [the migration work for 16](https://stylelint.io/migration-guide/to-16/) is scheduled for Jan-Feb.

This is great! Do you want to continue on your fork or should we create an org that can house this and similar repos? Something like, `a11y-devtools/stylelint-a11y`. There was also a discussion about using the namespace `@a11y` on NPM to publish these tools. What do you think?

**Comment by schalkneethling** [comment]
> I'm open for this and could be a co-maintainer. We use [my fork](https://github.com/ronilaukkarinen/stylelint-a11y/) in [our company](https://github.com/digitoimistodude) and I've been trying to keep my fork as up to date as I can. It's currently in stylelint 15 and [the migration work for 16](https://stylelint.io/migration-guide/to-16/) is scheduled for Jan-Feb.

Nice, I got this combination to work together: `stylelint@15.11.0 stylelint-config-recommended@13.0.0 @ronilaukkarinen/stylelint-a11y`

**Comment by ronilaukkarinen** [comment]
> > I'm open for this and could be a co-maintainer. We use [my fork](https://github.com/ronilaukkarinen/stylelint-a11y/) in [our company](https://github.com/digitoimistodude) and I've been trying to keep my fork as up to date as I can. It's currently in stylelint 15 and [the migration work for 16](https://stylelint.io/migration-guide/to-16/) is scheduled for Jan-Feb.
> 
> This is great! Do you want to continue on your fork or should we create an org that can house this and similar repos? Something like, `a11y-devtools/stylelint-a11y`. There was also a discussion about using the namespace `@a11y` on NPM to publish these tools. What do you think?

All fine with me. An org could be easier to manage. I also have active forks for following:

- [gulp-stylelint](https://github.com/ronilaukkarinen/gulp-stylelint)
- [stylefmt](https://github.com/ronilaukkarinen/stylefmt)

So could the org name be something that would open doors for maintaining even more style related packages without an active maintainers?

I had some other packages as well but the devs have recently woken up in their maintaining so my forks are therefore deprecated in those parts.

**Comment by ronilaukkarinen** [comment]
No they are not a11y related, but they are style/stylelint related and often have similar dependencies.

**Comment by schalkneethling** [comment]
> No they are not a11y related, but they are style/stylelint related and often have similar dependencies.
> […](#)
> On 1. Jan 2024 at 14.54 +0200, Schalk Neethling ***@***.***>, wrote: > > > I'm open for this and could be a co-maintainer. We use my fork in our company and I've been trying to keep my fork as up to date as I can. It's currently in stylelint 15 and the migration work for 16 is scheduled for Jan-Feb. > > This is great! Do you want to continue on your fork or should we create an org that can house this and similar repos? Something like, a11y-devtools/stylelint-a11y. There was also a discussion about using the namespace @a11y on NPM to publish these tools. What do you think? > All fine with me. An org could be easier to manage. I also have active forks for following: > > • gulp-stylelint > • stylefmt > > So could the org name be something that would open doors for maintaining even more style related packages without an active maintainers? Interesting question. I assume these will not all be accessibility related hence the question? Which did you have in mind? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

How about `stylechain` or `dev-tool-chain`?

**Comment by ronilaukkarinen** [comment]
Something like that would be great!

**Comment by schalkneethling** [comment]
> [ronilaukkarinen](/ronilaukkarinen)

I have set it up and invited you: https://github.com/developer-stylechain

**Comment by ronilaukkarinen** [comment]
Thanks @schalkneethling! I have transferred those repos I have under the new org 👍

**Comment by schalkneethling** [comment]
> Thanks @schalkneethling! I have transferred those repos I have under the new org 👍

Awesome! I will archive this one and point it to the new one. I will open a discussion on the new org to decide on how we will publish these on NPM i.e. the namespace we want to use - I guess either the full org name or just `stylechain` for short. But let's discuss it there.
